language: go

os:
  - linux

env:
  - GO111MODULE=on
  - DOCKER_COMPOSE_VERSION=1.24.1

go:
  - 1.12.x

# Get last commit
git:
  depth: 1

services:
  - docker

jobs:
  include:
    - stage: "Unit Tests"
      script: make unit-tests
    - stage: build
      script: make build
    - stage: "Integration Tests"
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      #This should get the image from a registry instead of build it again!
      install: make build
      script: make integration-tests
