language: go

os:
  - linux

env:
  - GO111MODULE=on

go:
  - 1.12.x

# Get last commit
git:
  depth: 1

services:
  - docker

jobs:
  include:
    - stage: "Unit Tests"
      script: make unit-tests
    - stage: build
      script: make build
    - stage: "Integration Tests"
      #This should get the image from a registry instead of build it again!
      install: make build
      script: make integration-tests
